"""
Core reconstruction module for Light Sheet Fluorescence Tomography.

Geometry
--------
- Capillary along X axis
- Light sheet in XY plane (thin in Z), generated by galvo scan along X
- Detection along Z: camera sees XY plane
- Sample rotated around X axis by angle θ

For a fixed X position, the light sheet selects z_lab ≈ 0.
A camera pixel at position y_lab measures fluorescence from the sample point:

    y_sample = y_lab · cos(θ)
    z_sample = y_lab · sin(θ)

This is a polar sampling of the YZ cross-section, where y_lab acts as
the radial coordinate r and θ is the polar angle. Reconstruction is
therefore a polar→Cartesian coordinate transformation (NOT an inverse
Radon transform, since we measure direct optical sections, not projections).
"""

import concurrent.futures
from typing import Optional, Tuple

import numpy as np
from scipy.ndimage import map_coordinates, median_filter, gaussian_filter


# ---------------------------------------------------------------------------
# Center of rotation estimation
# ---------------------------------------------------------------------------

def estimate_center_of_rotation(
    data: np.ndarray,
    x_slice: Optional[int] = None,
) -> float:
    """
    Estimate the center of rotation (CoR) offset in detector pixels.

    For a correctly centered rotation, the sinogram should be symmetric
    about the detector midpoint. We find the shift that minimizes the
    asymmetry between 0° and 180° projections.

    Parameters
    ----------
    data : np.ndarray
        Input array of shape (n_angles, n_x, n_y_lab).
    x_slice : int, optional
        X position to use for estimation. Defaults to middle.

    Returns
    -------
    float
        Center offset in pixels (positive = shift right).
    """
    n_angles, n_x, n_y = data.shape
    if x_slice is None:
        x_slice = n_x // 2

    # Use the middle X slice
    sinogram = data[:, x_slice, :]  # shape: (n_angles, n_y)

    # Compare opposite angles (0° vs 180°)
    half = n_angles // 2
    mid_y = n_y // 2
    max_shift = n_y // 4

    best_shift = 0
    best_error = np.inf

    for shift in range(-max_shift, max_shift + 1):
        error = 0.0
        count = 0
        for i in range(min(half, n_angles - half)):
            proj_0 = sinogram[i, :]
            proj_180 = sinogram[i + half, :]
            # At 180° offset, the projection should be mirrored
            proj_180_flip = proj_180[::-1]
            rolled = np.roll(proj_180_flip, 2 * shift)
            error += np.sum((proj_0 - rolled) ** 2)
            count += 1
        if count > 0:
            error /= count
        if error < best_error:
            best_error = error
            best_shift = shift

    return float(best_shift)


# ---------------------------------------------------------------------------
# Single-slice reconstruction (polar → Cartesian)
# ---------------------------------------------------------------------------

def reconstruct_slice(
    sinogram: np.ndarray,
    angles: np.ndarray,
    output_size: int,
    center_offset: float = 0.0,
    interpolation_order: int = 3,
) -> np.ndarray:
    """
    Reconstruct one YZ cross-section from its polar sampling.

    Parameters
    ----------
    sinogram : np.ndarray
        2D array of shape (n_angles, n_y_lab). Each row is the detector
        readout at one rotation angle.
    angles : np.ndarray
        Rotation angles in radians, shape (n_angles,).
    output_size : int
        Size of the output square image (output_size × output_size).
    center_offset : float
        Shift of rotation center relative to detector midpoint (in pixels).
    interpolation_order : int
        Spline interpolation order (1=linear, 3=cubic).

    Returns
    -------
    np.ndarray
        Reconstructed YZ cross-section of shape (output_size, output_size).
    """
    n_angles, n_y = sinogram.shape
    mid_y = n_y / 2.0 + center_offset

    # Maximum radius we can reconstruct
    r_max = min(mid_y, n_y - mid_y)

    # Build output Cartesian grid centered at (0, 0)
    coords = np.linspace(-r_max, r_max, output_size)
    ys_grid, zs_grid = np.meshgrid(coords, coords, indexing="xy")

    # Convert Cartesian → polar
    r_grid = np.sqrt(ys_grid**2 + zs_grid**2)
    theta_grid = np.arctan2(zs_grid, ys_grid)  # range [-π, π]

    # Ensure theta is in [0, 2π) for consistent lookup
    theta_grid = theta_grid % (2 * np.pi)

    # Map theta to sinogram angle index
    # angles should cover [0, π) or [0, 2π)
    angle_range = angles[-1] - angles[0] + (angles[1] - angles[0])

    if angle_range < 1.5 * np.pi:
        # 180° data: use symmetry. For theta in [π, 2π), map to
        # theta - π with negated r
        mask_upper = theta_grid >= np.pi
        theta_lookup = theta_grid.copy()
        r_lookup = r_grid.copy()
        theta_lookup[mask_upper] -= np.pi
        r_lookup[mask_upper] *= -1  # negative r = opposite side

        # Map theta to angle index
        angle_idx = (theta_lookup - angles[0]) / (angles[-1] - angles[0]) * (n_angles - 1)
        # Map r to y_lab pixel index (r can be negative now)
        y_idx = r_lookup + mid_y
    else:
        # 360° data: direct lookup
        angle_idx = (theta_grid - angles[0]) / (angles[-1] - angles[0]) * (n_angles - 1)
        y_idx = r_grid + mid_y  # r is always positive here

    # Mask outside valid radius
    valid_mask = r_grid <= r_max

    # Interpolate from sinogram
    coords_interp = np.array([angle_idx.ravel(), y_idx.ravel()])
    recon_flat = map_coordinates(
        sinogram,
        coords_interp,
        order=interpolation_order,
        mode="constant",
        cval=0.0,
    )
    recon = recon_flat.reshape(output_size, output_size)
    recon[~valid_mask] = 0.0

    return recon


# ---------------------------------------------------------------------------
# Full 3D volume reconstruction
# ---------------------------------------------------------------------------

def reconstruct_volume(
    data: np.ndarray,
    angle_start: float = 0.0,
    angle_stop: float = 180.0,
    center_offset: float = 0.0,
    auto_center: bool = True,
    output_size: Optional[int] = None,
    downsample: float = 1.0,
    interpolation_order: int = 3,
    pre_filter_sigma: float = 0.0,
    post_filter_sigma: float = 0.0,
    n_workers: int = 4,
    progress_callback=None,
) -> np.ndarray:
    """
    Reconstruct 3D volume from rotational light-sheet data.

    Parameters
    ----------
    data : np.ndarray
        Input data of shape (n_angles, n_x, n_y_lab).
    angle_start : float
        Start angle in degrees.
    angle_stop : float
        Stop angle in degrees (exclusive of last step).
    center_offset : float
        Manual center offset in pixels.
    auto_center : bool
        If True, estimate center of rotation automatically.
    output_size : int, optional
        Output YZ slice size. Defaults to n_y_lab.
    downsample : float
        Downsample factor (< 1 reduces resolution for speed).
    interpolation_order : int
        Spline order for interpolation (1=linear, 3=cubic).
    pre_filter_sigma : float
        Gaussian pre-filter sigma on sinograms (0 = off).
    post_filter_sigma : float
        Gaussian post-filter sigma on reconstructed volume (0 = off).
    n_workers : int
        Number of parallel threads.
    progress_callback : callable, optional
        Called with (current_slice, total_slices) for progress reporting.

    Returns
    -------
    np.ndarray
        Reconstructed volume of shape (n_x, output_size, output_size)
        representing (X, Y_sample, Z_sample).
    """
    data = np.asarray(data, dtype=np.float32)
    if data.ndim != 3:
        raise ValueError(
            f"Reconstruction expects a 3D stack (n_angles, n_x, n_y_lab), "
            f"but got a {data.ndim}D array of shape {data.shape}."
        )
    n_angles, n_x, n_y = data.shape
    if n_angles < 2:
        raise ValueError(
            f"Reconstruction needs at least 2 rotation angles, but the first "
            f"axis has size {n_angles} (input shape {data.shape}). The rotation "
            f"angle must be the FIRST axis: (n_angles, n_x, n_y_lab). If your "
            f"stack has the angle on another axis, transpose it; if you selected "
            f"a single frame or a reconstructed volume, pick the rotational "
            f"stack layer instead."
        )

    # Downsample if requested
    if downsample < 1.0:
        from skimage.transform import rescale
        # Downsample spatial dimensions only
        data_ds = np.zeros(
            (n_angles, int(n_x * downsample), int(n_y * downsample)),
            dtype=np.float32,
        )
        for i in range(n_angles):
            data_ds[i] = rescale(
                data[i], downsample, anti_aliasing=True, preserve_range=True
            )
        data = data_ds
        n_angles, n_x, n_y = data.shape
        center_offset *= downsample

    # Rotation angles
    angles = np.linspace(
        np.radians(angle_start),
        np.radians(angle_stop),
        n_angles,
        endpoint=False,
    )

    # Auto-center
    if auto_center:
        estimated = estimate_center_of_rotation(data)
        center_offset += estimated

    if output_size is None:
        output_size = n_y

    # Pre-filter sinograms
    if pre_filter_sigma > 0:
        for i in range(n_x):
            for a in range(n_angles):
                data[a, i, :] = gaussian_filter(
                    data[a, i, :], sigma=pre_filter_sigma
                )

    # Reconstruct each X slice in parallel
    volume = np.zeros((n_x, output_size, output_size), dtype=np.float32)

    def _recon_one(ix):
        sinogram = data[:, ix, :]  # shape: (n_angles, n_y)
        return ix, reconstruct_slice(
            sinogram, angles, output_size, center_offset, interpolation_order
        )

    with concurrent.futures.ThreadPoolExecutor(max_workers=n_workers) as executor:
        futures = {executor.submit(_recon_one, ix): ix for ix in range(n_x)}
        done = 0
        for future in concurrent.futures.as_completed(futures):
            ix, recon = future.result()
            volume[ix] = recon
            done += 1
            if progress_callback:
                progress_callback(done, n_x)

    # Post-filter
    if post_filter_sigma > 0:
        volume = gaussian_filter(volume, sigma=post_filter_sigma)

    # Normalize to [0, 1]
    vmin, vmax = np.percentile(volume[volume > 0], [1, 99]) if np.any(volume > 0) else (0, 1)
    if vmax > vmin:
        volume = np.clip((volume - vmin) / (vmax - vmin), 0, 1)

    return volume
